apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: openshift-operators
spec:
  channel: latest
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
