apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: rhacs-central-services
  namespace: rhacs
spec:
  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      # When using Plaintext (8080) default routes should be enabled: false
      route:
        enabled: false
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
    persistence:
      persistentVolumeClaim:
        claimName: rhacs-db
  customize:
    envVars:
      - name: ROX_PLAINTEXT_ENDPOINTS
        value: http@8080
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: Enabled
# If Router uses certificates from own PKI or self-sigend-certificates
  # tls:
  #   additionalCAs:
  #     - content: >-
  #         <CA_PEM>
  #       name: ca.crt
  #     - content: >-
  #         <SUB_CA_PEM>
  #       name: sub-ca.crt
